### ISSUE TITLE
Created a base Data Domain model

### ISSUE THREAD

**Issue by eb4i** [eb4i/the_pattern_office#3]
As a data domain owner, I want to create a domain configuration with a name, URL, abbreviation, and zone, so that I can specify the parameters for my data domain.

```
metadata:
  description: 'A sample data domain specification'
  distribution: 'Global'
  version: 'v0.4'
  last_updated: '2023-04-07'
  contact: 'support@example.com'

domain:
  name: domain_name
  abbreviation:
  zone: zone_name
  description:
  location:
```
