### ISSUE TITLE
Created an Abstract Base Model

### ISSUE THREAD

**Issue by eb4i** [eb4i/the_pattern_office#4]
As a Developer, I want to create a simple starter base model that has inheritable attributes  

```
metadata:
  description: 'A sample data domain specification'
  distribution: 'Global'
  version: 'v0.4'
  last_updated: '2023-04-07'
  contact: 'support@example.com'
```
